services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: paperless_postgres
      POSTGRES_PASSWORD: paperless
    ports:
      - "5432:5432"
  adminer:
    image: adminer:fastcgi
    restart: always
    ports:
      - "9091:8080"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "9093:15672"
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"
      - "rabbitmq-log:/var/log/rabbitmq"

volumes:
  rabbitmq-data:
    driver: local
  rabbitmq-log:
    driver: local
