services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: paperless
      POSTGRES_USER: swkom
    ports:
      - "5432:5432"
  adminer:
    image: adminer:fastcgi
    restart: always
    ports:
      - "9091:8080"
