services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: paperless_postgres
      POSTGRES_PASSWORD: paperless
    ports:
      - "5432:5432"
  adminer:
    image: adminer:fastcgi
    restart: always
    ports:
      - "9091:8080"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "9093:15672"
    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"
      - "rabbitmq-log:/var/log/rabbitmq"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: paperless_minio
      MINIO_ROOT_PASSWORD: paperless
    command: server --console-address ":9001" /data

volumes:
  rabbitmq-data: {}
  rabbitmq-log: {}
  minio_storage: {}
