# see https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
name: main-ci
run-name: "MAIN CI running"
on: #the action runs on push against main
    push:
      branches:
        - main
        - 'feature/7-add-github-actions-to-trigger-the-cicd'

jobs:
  test_paperlessREST:
    runs-on: ubuntu-22.04
    defaults: #we want to execute the following commands in the directory containing the java project
      run:
        working-directory: paperlessREST
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4
      - name: Set up JDK 17
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          architecture: x64
          cache: maven #we cache the maven packages, so that we do not have to fetch them at every job run
      - run: mvn -B test --file pom.xml
